name: navigation_stack_previewer
description: "A visual navigation stack previewer for Flutter. Swipe down from the top to see real-time screenshots of your navigation history and navigate back instantly by tapping on them."
version: 0.0.5
repository: https://github.com/kunal311997/navigation_stack_previewer.git
issue_tracker: https://github.com/kunal311997/navigation_stack_previewer/issues

topics:
  - navigation
  - debugging
  - developer-tools
  - screenshots
  - ui-ux

screenshots:
  - description: 'Carousel layout showing navigation history with screenshots.'
    path: Screenshot_20260419_103316.png
  - description: 'List layout showing navigation history.'
    path: Screenshot_20260419_180223.png
  - description: 'Enlarged preview of a specific screen from the history.'
    path: Screenshot_20260419_103325.png

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: avenirltstd
      fonts:
        - asset: assets/avenirltstd_light.otf
