name: navigation_stack_previewer
description: "A visual navigation stack previewer for Flutter. Swipe down from the top to see real-time screenshots of your navigation history and navigate back instantly by tapping on them."
version: 0.0.3
repository: https://github.com/kunal311997/navigation_stack_previewer.git
issue_tracker: https://github.com/kunal311997/navigation_stack_previewer/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
